### ISSUE TITLE
CloudFormation update fails on GSI changes

### ISSUE THREAD

**Issue by mattmanning** [convox/console-app#9]
**To reproduce:**

- Launch a new stack using the version of formation.json at [this commit](https://github.com/convox/console-app/blob/76e04c79de02abb7ba834de5a7bd794135a8c01d/formation.json).
- Wait for the stack creation to complete, then update the stack from the latest version of formation.json

**Expected results:**

Dynamo table updates

**Actual Results:**

CloudFormation fails with the error: `Cannot perform more than one GSI creation or deletion in a single update` and the update rolls back.

This is the attempted changeset:

<img width="360" alt="screen_shot_2016-09-09_at_11 29 25_am_720" src="https://cloud.githubusercontent.com/assets/44615/18401977/498e195a-76ab-11e6-91a5-5f71638348fc.png">

This doc has some info that says changes can't be made to indexes on multiple tables at once: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html, but I'm seeing the error even when the change is to the same table (I think).

**Comment by mattmanning** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;LxEumhnO&#x2F;686-arthrex-dynamo-stack-update-problems"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Arthrex Dynamo Stack Update problems</a>

**Comment by ddollar** [comment]
Worked around
